name: Build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build Binary File
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Check out
        uses: actions/checkout@v2

      - name: Build
        run: make build